---
ID: "6eefa78d-dc68-4948-b84b-25027dadcc3c"
Parent: "c2c57683-217b-496a-a7ac-6a85d921c0ab"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/SampleFeature/Sample Content Categories Variants/$name/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190515T131721Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
